from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

def apply_designer_styling(prs):
    """
    Applies a modern/dark theme to the presentation.
    """
    # 1. Slide Master Modifications (Background)
    # Note: python-pptx doesn't support full master slide editing easily 
    # for all background types, but we can iterate through layouts.
    
    # We will apply background color to each slide individually for maximum control
    return prs

THEMES = {
    "midnight": {
        "BG_COLOR": RGBColor(20, 20, 30),
        "TITLE_COLOR": RGBColor(255, 200, 0),
        "TEXT_COLOR": RGBColor(240, 240, 240),
        "ACCENT_COLOR": RGBColor(0, 150, 255)
    },
    "ocean": {
        "BG_COLOR": RGBColor(10, 45, 60),
        "TITLE_COLOR": RGBColor(0, 255, 200),
        "TEXT_COLOR": RGBColor(230, 250, 255),
        "ACCENT_COLOR": RGBColor(0, 180, 220)
    },
    "minimal": {
        "BG_COLOR": RGBColor(255, 255, 255),
        "TITLE_COLOR": RGBColor(0, 0, 0),
        "TEXT_COLOR": RGBColor(60, 60, 60),
        "ACCENT_COLOR": RGBColor(100, 100, 100)
    },
    "sunset": {
        "BG_COLOR": RGBColor(45, 10, 50),
        "TITLE_COLOR": RGBColor(255, 120, 0),
        "TEXT_COLOR": RGBColor(255, 240, 230),
        "ACCENT_COLOR": RGBColor(180, 50, 200)
    }
}

def create_styled_presentation(slides_data, theme_name="midnight"):
    """
    Creates a styled PowerPoint presentation from structured data using a theme.
    """
    prs = Presentation()
    
    # Select Theme
    theme = THEMES.get(theme_name, THEMES["midnight"])
    BG_COLOR = theme["BG_COLOR"]
    TITLE_COLOR = theme["TITLE_COLOR"]
    TEXT_COLOR = theme["TEXT_COLOR"]
    ACCENT_COLOR = theme["ACCENT_COLOR"]
    
    # --- 1. Title Slide ---
    slide = prs.slides.add_slide(prs.slide_layouts[0]) # Title Slide
    
    # Set Background
    background = slide.background
    fill = background.fill
    fill.solid()
    fill.fore_color.rgb = BG_COLOR
    
    # Title Text
    title = slide.shapes.title
    title.text = "Document Summary"
    title.text_frame.paragraphs[0].font.color.rgb = TITLE_COLOR
    title.text_frame.paragraphs[0].font.name = "Calibri Light"
    title.text_frame.paragraphs[0].font.size = Pt(54)
    title.text_frame.paragraphs[0].alignment = PP_ALIGN.CENTER
    
    # Subtitle Text
    subtitle = slide.placeholders[1]
    subtitle.text = "Generated by IntelliDoc AI \n(Powered by Gemini)"
    subtitle.text_frame.paragraphs[0].font.color.rgb = TEXT_COLOR
    subtitle.text_frame.paragraphs[0].font.name = "Calibri"
    subtitle.text_frame.paragraphs[0].font.size = Pt(24)
    subtitle.text_frame.paragraphs[0].alignment = PP_ALIGN.CENTER
    
    # Add a decorative shape (Line or Rectangle)
    shape = slide.shapes.add_shape(
        1, # msoShapeRectangle
        Inches(0), Inches(0), Inches(0.5), prs.slide_height
    )
    shape.fill.solid()
    shape.fill.fore_color.rgb = ACCENT_COLOR
    shape.line.fill.background() # No line

    # --- 2. Content Slides ---
    for slide_data in slides_data:
        # Use Blank Layout for custom control, or Title Only (5)
        slide = prs.slides.add_slide(prs.slide_layouts[5]) # Title Only
        
        # Set Background
        background = slide.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = BG_COLOR
        
        # Title
        title_shape = slide.shapes.title
        title_shape.text = slide_data.get("title", "Slide")
        title_shape.text_frame.paragraphs[0].font.color.rgb = TITLE_COLOR
        title_shape.text_frame.paragraphs[0].font.name = "Calibri Light"
        title_shape.text_frame.paragraphs[0].font.size = Pt(40)
        title_shape.text_frame.paragraphs[0].alignment = PP_ALIGN.LEFT
        
        # Add decorative bar under title
        bar = slide.shapes.add_shape(
            1, Inches(0.5), Inches(1.5), Inches(9), Inches(0.05)
        )
        bar.fill.solid()
        bar.fill.fore_color.rgb = ACCENT_COLOR
        bar.line.fill.background()

        # Content Text Box
        left = Inches(0.5)
        top = Inches(1.8)
        width = Inches(9)
        height = Inches(5)
        
        txBox = slide.shapes.add_textbox(left, top, width, height)
        tf = txBox.text_frame
        tf.word_wrap = True
        
        bullets = slide_data.get("bullets", [])
        for i, bullet in enumerate(bullets):
            p = tf.add_paragraph()
            p.text = str(bullet) # Ensure string
            p.font.name = "Calibri"
            p.font.size = Pt(24)
            p.font.color.rgb = TEXT_COLOR
            p.level = 0
            p.space_after = Pt(14) # Add spacing
            
        # Add Speaker Notes
        if "speaker_notes" in slide_data and slide.has_notes_slide:
            notes_slide = slide.notes_slide
            text_frame = notes_slide.notes_text_frame
            text_frame.text = slide_data["speaker_notes"]
            
    return prs
